ALTER TABLE users
ADD email VARCHAR(100) NOT NULL;

ALTER TABLE users
ADD phone VARCHAR(30);

ALTER TABLE users
MODIFY name VARCHAR(50) NOT NULL;

ALTER TABLE users
MODIFY lastname VARCHAR(50) NOT NULL;

ALTER TABLE users
ADD CONSTRAINT unique_email UNIQUE (email);
